version: "3.8"

services:
  nodejs:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: nodejs_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - mysql
      - redis
    command: ["tmux", "new-session", "-d", "npm", "start"]

  mysql:
    image: mysql:5.7
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: myapp
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:6.0.7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"

  redis_insight:
    image: redislabs/redisinsight:latest
    container_name: redis_insight
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - redis
    volumes:
      - redis_insight_data:/db



volumes:
  mysql_data:
  redis_insight_data:
